// Mock data — fictional entries to demonstrate the UI
// Dates are days-ago so we can compute expiry status realistically.

const CATEGORIES = [
  { id: "all", name: "All Vaults", color: "oklch(0.86 0.20 142)" },
  { id: "work", name: "Work", color: "oklch(0.86 0.20 142)" },
  { id: "personal", name: "Personal", color: "oklch(0.82 0.14 215)" },
  { id: "finance", name: "Finance", color: "oklch(0.82 0.16 75)" },
  { id: "dev", name: "Developer", color: "oklch(0.76 0.18 290)" },
  { id: "social", name: "Social", color: "oklch(0.76 0.18 340)" },
];

// breachStatus: "safe" | "compromised" | "unchecked"
// daysOld: how long ago the password was set (for expiry math)
// expiryDays: 30/60/90/never

const ACCOUNTS = [
  {
    id: "acc-01",
    name: "Helix Cloud",
    domain: "console.helixcloud.io",
    email: "n.maren@cipherline.dev",
    username: "n.maren",
    password: "rT9$mZeq!4kVc8L",
    note: "Production root account. Hardware key required for billing changes.",
    category: "work",
    tags: ["2FA", "Critical"],
    color: "oklch(0.86 0.20 142)",
    initial: "H",
    lastUsed: "2h ago",
    daysOld: 18,
    expiryDays: 90,
    breachStatus: "safe",
    breachCount: 0,
  },
  {
    id: "acc-02",
    name: "Northbeam Bank",
    domain: "secure.northbeambank.com",
    email: "naomi.maren@proton.me",
    username: "nmaren_88",
    password: "Q7p#Lz!93B$mVxq2",
    note: "Personal checking. Notifications routed to family inbox.",
    category: "finance",
    tags: ["2FA", "MFA"],
    color: "oklch(0.82 0.16 75)",
    initial: "N",
    lastUsed: "yesterday",
    daysOld: 56,
    expiryDays: 60,
    breachStatus: "safe",
    breachCount: 0,
  },
  {
    id: "acc-03",
    name: "Orbital Repo",
    domain: "orbital.repo.dev",
    email: "n.maren@cipherline.dev",
    username: "maren",
    password: "ghp_8FxQ2nLm4PpKvR9",
    note: "Personal access token — read/write to private orgs. Rotate Q2.",
    category: "dev",
    tags: ["Token", "SSH"],
    color: "oklch(0.76 0.18 290)",
    initial: "O",
    lastUsed: "12m ago",
    daysOld: 12,
    expiryDays: 90,
    breachStatus: "compromised",
    breachCount: 12483,
  },
  {
    id: "acc-04",
    name: "Mosaic Studio",
    domain: "team.mosaic.design",
    email: "naomi@studio.mosaic.design",
    username: "naomi.m",
    password: "Summer2024!",
    note: "Shared design seat — keep prototypes in archive only.",
    category: "work",
    tags: ["Shared"],
    color: "oklch(0.76 0.18 340)",
    initial: "M",
    lastUsed: "3d ago",
    daysOld: 142,
    expiryDays: 90,
    breachStatus: "compromised",
    breachCount: 47,
  },
  {
    id: "acc-05",
    name: "Driftwood Mail",
    domain: "mail.driftwood.app",
    email: "naomi.maren@driftwood.app",
    username: "naomi.maren",
    password: "wH4!pT7nQz#m2Rb9",
    note: "Backup recovery inbox — keep separate from primary device.",
    category: "personal",
    tags: ["Recovery", "2FA"],
    color: "oklch(0.82 0.14 215)",
    initial: "D",
    lastUsed: "5h ago",
    daysOld: 8,
    expiryDays: 60,
    breachStatus: "unchecked",
    breachCount: 0,
  },
  {
    id: "acc-06",
    name: "Lumen Forum",
    domain: "forum.lumen.community",
    email: "naomi.maren@driftwood.app",
    username: "naomi",
    password: "Summer2024!",
    note: "Community account. Low-stakes — but reusing this password.",
    category: "social",
    tags: ["Public"],
    color: "oklch(0.76 0.18 340)",
    initial: "L",
    lastUsed: "2w ago",
    daysOld: 64,
    expiryDays: 90,
    breachStatus: "unchecked",
    breachCount: 0,
  },
];

export { CATEGORIES, ACCOUNTS };
