// Mock data — fictional entries to demonstrate the UI
// Dates are days-ago so we can compute expiry status realistically.

const CATEGORIES = [
  { id: "all", name: "All Vaults", color: "oklch(0.86 0.20 142)" },
  { id: "work", name: "Work", color: "oklch(0.86 0.20 142)" },
  { id: "personal", name: "Personal", color: "oklch(0.82 0.14 215)" },
  { id: "finance", name: "Finance", color: "oklch(0.82 0.16 75)" },
  { id: "dev", name: "Developer", color: "oklch(0.76 0.18 290)" },
  { id: "social", name: "Social", color: "oklch(0.76 0.18 340)" },
];

// breachStatus: "safe" | "compromised" | "unchecked"
// daysOld: how long ago the password was set (for expiry math)
// expiryDays: 30/60/90/never

const ACCOUNTS = [
  {
    id: "acc-01",
    name: "GitHub",
    domain: "github.com",
    email: "jenny@cipherline.dev",
    username: "jenny_dev",
    password: "Gh7#mPx!K9vR2z",
    note: "Personal access token — read/write to private orgs. Rotate quarterly.",
    category: "dev",
    tags: ["2FA", "Token"],
    color: "oklch(0.76 0.18 290)",
    initial: "G",
    lastUsed: "12m ago",
    daysOld: 18,
    expiryDays: 90,
    breachStatus: "safe",
    breachCount: 0,
  },
  {
    id: "acc-02",
    name: "Netflix",
    domain: "netflix.com",
    email: "jenny@email.com",
    username: "jenny@email.com",
    password: "Summer2024!",
    note: "Family plan — shared with household. Password needs rotating.",
    category: "personal",
    tags: ["Shared"],
    color: "oklch(0.82 0.14 215)",
    initial: "N",
    lastUsed: "3d ago",
    daysOld: 142,
    expiryDays: 90,
    breachStatus: "compromised",
    breachCount: 47,
  },
  {
    id: "acc-03",
    name: "Notion",
    domain: "notion.so",
    email: "jenny@cipherline.dev",
    username: "jenny_dev",
    password: "N0t!0nK9xQz#mR",
    note: "Team workspace admin — invite links expire after 7 days.",
    category: "work",
    tags: ["2FA"],
    color: "oklch(0.86 0.20 142)",
    initial: "N",
    lastUsed: "yesterday",
    daysOld: 57,
    expiryDays: 60,
    breachStatus: "safe",
    breachCount: 0,
  },
  {
    id: "acc-04",
    name: "Figma",
    domain: "figma.com",
    email: "jenny@cipherline.dev",
    username: "jenny.design",
    password: "Summer2024!",
    note: "Design team seat — reusing same password as Netflix!",
    category: "work",
    tags: ["Shared"],
    color: "oklch(0.76 0.18 340)",
    initial: "F",
    lastUsed: "5h ago",
    daysOld: 30,
    expiryDays: 0,
    breachStatus: "unchecked",
    breachCount: 0,
  },
  {
    id: "acc-05",
    name: "Dropbox",
    domain: "dropbox.com",
    email: "jenny@email.com",
    username: "jenny_backup",
    password: "Dr0pB0x!7kQzXm",
    note: "Cloud backup — 2TB plan. Recovery key stored offline.",
    category: "personal",
    tags: [],
    color: "oklch(0.82 0.14 215)",
    initial: "D",
    lastUsed: "1w ago",
    daysOld: 5,
    expiryDays: 0,
    breachStatus: "unchecked",
    breachCount: 0,
  },
  {
    id: "acc-06",
    name: "LinkedIn",
    domain: "linkedin.com",
    email: "jenny@email.com",
    username: "jenny@email.com",
    password: "L!nk3dIn9xQzMr",
    note: "Professional profile — public visibility. Connected to company SSO.",
    category: "social",
    tags: ["Public"],
    color: "oklch(0.76 0.18 340)",
    initial: "L",
    lastUsed: "2h ago",
    daysOld: 8,
    expiryDays: 0,
    breachStatus: "compromised",
    breachCount: 12483,
  },
];

export { CATEGORIES, ACCOUNTS };
